services:
  amazon-ads-mcp:
    # Use pre-built image from GitHub Container Registry (recommended)
    # This automatically pulls the latest stable version
    image: ghcr.io/netzsicht/amazon_ads_mcp:latest

    # Alternative: Build locally (uncomment to use local build)
    # build:
    #   context: .
    #   dockerfile: Dockerfile

    container_name: amazon-ads-mcp
    env_file:
      - .env
    environment:
      # Server runtime
      - TRANSPORT=http
      - HOST=0.0.0.0
      - PORT=9080
      - LOG_LEVEL=INFO
      - AMAZON_AD_PACKAGES=profiles,accounts-ads-accounts
      - AMAZON_ADS_TOKEN_PERSIST=true
      - AMAZON_ADS_CACHE_DIR=/app/.cache/amazon-ads-mcp
      # Authentication (configure as needed for your environment)
      # - AUTH_METHOD=openbridge

    ports:
      - "9080:9080"
    volumes:
      # Persist downloaded exports/reports
      - downloads:/app/data
      # Persist token cache across container restarts
      - cache:/app/.cache
    command: [
      "python", "-m", "amazon_ads_mcp.server",
      "--transport", "${TRANSPORT:-http}",
      "--host", "${HOST:-0.0.0.0}",
      "--port", "${PORT:-9080}"
    ]
 
volumes:
  downloads: {}
  cache: {}
